### ISSUE TITLE
Modifying payload hash causes server crash

### ISSUE THREAD

**Issue by ameesters** [frbuceta/restify-jwt-community#2]
When tempering with the second part of the JWT we get a `SyntaxError: Unexpected token  in JSON at position 28` causing a crash which could cause a malicious user to utillize that as a DoS attack.

REPRO:

when we have a JWT: 
```
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWV9.TJVA95OrM7E2cBab30RMHrHDcEfxjoYZgeFONFh7HgQ
```

And add some random noise to the payload part:
```
eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIrandomnoiseMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWV9.TJVA95OrM7E2cBab30RMHrHDcEfxjoYZgeFONFh7HgQ
```

it results in the following stacktrace:

```
users_1           | SyntaxError: Unexpected token  in JSON at position 28
users_1           |     at JSON.parse (<anonymous>)
users_1           |     at Object.jwsDecode [as decode] (/usr/src/services/users/node_modules/jws/lib/verify-stream.js:71:20)
users_1           |     at Object.module.exports [as decode] (/usr/src/services/users/node_modules/jsonwebtoken/decode.js:5:21)
users_1           |     at middleware (/usr/src/services/users/node_modules/restify-jwt-community/lib/index.js:70:24)
users_1           |     at Server.<anonymous> (/usr/src/services/users/node_modules/express-unless/index.js:47:5)
users_1           |     at next (/usr/src/services/users/node_modules/restify/lib/server.js:992:30)
users_1           |     at f (/usr/src/services/users/node_modules/once/once.js:36:25)
users_1           |     at Server.parseQueryString (/usr/src/services/users/node_modules/restify/lib/plugins/query.js:28:20)
users_1           |     at next (/usr/src/services/users/node_modules/restify/lib/server.js:992:30)
users_1           |     at f (/usr/src/services/users/node_modules/once/once.js:36:25)
```

What i would have expected was a TokenInvalid response or something

**Comment by frbuceta** [comment]
The problem comes from the Json Web Signature that is dependency on the Json Web Token

**Comment by ameesters** [comment]
Ok, so are you coordinating with the upstream package `jsonwebtoken` or should i?

**Comment by frbuceta** [comment]
I've put an issue in the Jws, you can put it in the Jwt
